version: '3.9'

name: golang-gorm-postgres-gin
services:
  devcontainer:
    container_name: rest-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    hostname: rest-server
    # networks:
    #   - mynet      
    volumes:
      - ./:/app

  # postgres and postgres admin services :
  db:
    image: postgres:14-alpine
    container_name: ${DB_CONTAINER_NAME:-mydb}
    hostname: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    # networks:
    #   - mynet
    ports:
      - 5434:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped

  db_webadmin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

# volumes:
#   roach:

# networks:
#   mynet:
#     driver: bridge      